game.splash("Welcome to anntis city your free to run around")
let Annt = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . 3 3 . . . . . . . . . . . 
    . . 3 3 3 3 3 3 3 3 . . . . . . 
    . . 3 . . . . . . 3 . . . . . . 
    . . 3 . f . . f . 3 . . . . . . 
    . . 3 f . . . . f 3 . . . . . . 
    . . 3 . f f f f . 3 . . . . . . 
    . . 3 . . . . . . 3 . . . . . . 
    . 3 3 6 6 3 . . 6 3 . . . . . . 
    . 6 6 6 6 6 3 3 6 6 6 6 . . . . 
    . 6 6 6 6 6 6 6 6 6 6 6 . . . . 
    . 6 6 6 6 6 6 6 6 6 6 . . . . . 
    . . . 6 6 6 6 6 6 . . . . . . . 
    . . . 6 6 6 . . 6 . . . . . . . 
    . . . 6 6 . . . 6 . . . . . . . 
    . . . . 6 . . . 6 . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Annt)
scene.setBackgroundColor(14)
Annt.setBounceOnWall(true)
let Nowa = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
